project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  google-analytics: "G-XY7N52R9B3"
  title: "Oleksandra Dreval: Motion Graphics Design and animation"
  description: "Oleksandra Dreval is a Vancouver-based Motion Graphics and VFX artist, UE5 Generalist specializing in 2D/3D animation, branding and demo reels for TV, games, marketing and digital media."
  image:  src/images/MyLogoColour_YouTube.jpg
  favicon:  src/images/MyLogoColour_YouTube.jpg
  back-to-top-navigation: true
  page-navigation: true
  search: false
  navbar:
    background: "#000000"
    foreground: white
    logo: src/images/MyLogoColour_YouTube.jpg
    logo-alt: "Oleksandra Dreval Motion Graphics Designer Vancouver"
    title: false
    collapse-below: lg
    right:
      - text: "About"
        href: about.qmd
      - text: "Home"
        href: index.qmd
      - text: "Motion Graphics & VFX"
        menu:
        - text: "Motion Graphics"
          href: motion-graphics.qmd
        - text: "CG & Breakdowns"
          href: compositing_breakdowns.qmd
        - text: "Digital Media"
          href: digital_media.qmd
      - text: "Graphic design & GFX"
        menu:
        - text: "Graphic design & Social media GFX"
          href: graphic_design_social_media_gfx.qmd
        - text: "Print & Branding"
          href: print_branding.qmd
        - text: "Web Design & UI/UX"
          href: web_uiux.qmd
      - text: "Art"
        menu:
        - text: "Character Design"
          href: character_design.qmd
        - text: "Illustrations & Digital"
          href: illustrations_digital.qmd

  page-footer:
    background: "#000000"
    left: "Copyright 2025, Oleksandra Dreval"
    right:
      - icon: home
        href: https://oleksadreval.com
      - icon: linkedin
        href: https://www.linkedin.com/in/oleksadreval

format:
  html:
    toc: false
    grid:
      margin-width: 100px

meta:
  - name: "keywords"
    content: "motion graphics, Vancouver, graphic design, graphic designer, 3D animation, visual effects, CGI, VFX, after effects, branding, digital art"
